# Generated by Django 5.2.1 on 2025-07-23 14:30

import App.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_appuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='profile_pic',
            field=models.ImageField(blank=True, help_text='Upload a profile picture (max 5MB, formats: JPG, PNG, GIF, WEBP)', null=True, upload_to='profile_pics/', validators=[App.validators.validate_profile_image]),
        ),
    ]
