# Generated by Django 5.2.1 on 2025-07-24 07:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_alter_appuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload a profile picture (max 5MB, formats: JPG, PNG, GIF, WEBP)', max_length=255, null=True, verbose_name='image'),
        ),
    ]
