# Generated by Django 5.2.1 on 2025-07-26 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_alter_appuser_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startercode',
            old_name='base_code_js',
            new_name='base_code_c',
        ),
    ]
