# Generated by Django 5.2.1 on 2025-08-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_rename_base_code_js_startercode_base_code_c'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubmission',
            name='is_history',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='SubmissionHistory',
        ),
    ]
